name: build_ErfanGSIs

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL: https://aecem6wlnrwrtwrb.node.ppio.cloud:17414/fsa167af8c.a.bdydns.com/1435501072/Firmware/Flyme/note9/7.3.0.0/cn/20190827203134/fd94b6a7/update.zip?f_ver=v1&max_age=7776000&r=JjAbOzBiYRkCJjU3GjYqHGApCiI5LWBVCyJoHAQlNQ4vNgpkBTQ3WwFgKTUZMmFWeWpcZXN2fhkHIWhoXWZhSXZ2WHlza38FUGAhPlRjOk8vc0A%2BMzwvQgFhPTMdITQKJSA8IAcLPyI0DjM2SA%3D%3D&ppiouid=62f5cbfb83c32f000133fea8758827d2&ppio_auth=62f5cbfb__62c95678_d94b4b6d1afc942f64b2b8e8f094397d
  ROM_NAME: Flyme
  BUILD_TYPE: ab
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
           
       - name: Initialization environment
         run: |
            sudo -E apt-get -qq install git wget
       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/erfanoabdi/ErfanGSIs.git ErfanGSIs
         
       - name: Fix exit
         run: |
              sed -i 's/\|\| exit 1//g' $GITHUB_WORKSPACE/ErfanGSIs/url2GSI.sh
              sed -i 's/exit 1//g' $GITHUB_WORKSPACE/ErfanGSIs/url2GSI.sh
       
       - name: Setting up ErfanGSI requirements
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs
              mkdir ./output
              sudo apt install unace unrar zip unzip p7zip-full p7zip-rar sharutils rar uudeview mpack arj cabextract file-roller device-tree-compiler liblzma-dev python3-pip brotli liblz4-tool gawk aria2
              pip install backports.lzma protobuf pycrypto
       
       - name: Download Stock Rom & Generate GSI
         run: |
              cd  $GITHUB_WORKSPACE/ErfanGSIs
              sudo bash ./url2GSI.sh -c --$BUILD_TYPE $ROM_URL $ROM_NAME
       
       - name: Zip GSI  
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs/output
              mkdir final
              zip -r final/GSI.zip ./*
       
       - name: Upload GSI to WeTransfer
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs/output
              curl -sL https://git.io/file-transfer | sh
              ./transfer wet ./final/GSI.zip

         
            
